model:
  base_learning_rate: 1.0e-4
  cond_prob: 0.7
  eval_freq: 10000
  eval_samples : 4
  log_freq: 1000
  resume: False
  max_iter: 1000000
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    log_every_t: 200
    timesteps: 1000
    w: 0

    dit_config:
      input_size: 32
      in_channels: 4
      hidden_size: 768
      depth: 12
      num_heads: 12
      max_seq_len: 4096
      learn_sigma: False